version: '3.8'

services:
  web:
    build: .
    container_name: fastapi_app
    ports:
      - "7001:7001"
    volumes:
      - .:/app
    environment:
      - ENV=development
    command: >
      bash -c "source env/bin/activate && 
               uvicorn app.main:app --host 0.0.0.0 --port 7001"
